'use client';
import { useState } from 'react';
import { ArrowDown, ArrowUpRight, Code2, Cpu, Mail, MessageCircle, Smartphone, Bot, Layers3, Check, MoveHorizontal, GraduationCap, Briefcase, Star } from 'lucide-react';
import { projects, type Project } from '@/lib/projects.ts';
import { ProjectCard } from '@/components/project-card.tsx';
import { ProjectSpotlight } from '@/components/project-spotlight.tsx';
import { ProjectDialog } from '@/components/project-dialog.tsx';
import { Reveal } from '@/components/reveal.tsx';

// Inline SVG icons not available in this lucide-react version
const GithubIcon = ({ size = 20 }: { size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
    <path d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" />
  </svg>
);

const LinkedinIcon = ({ size = 20 }: { size?: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
    <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 01-2.063-2.065 2.064 2.064 0 112.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
  </svg>
);


const spotlightProjects = [projects.find(p => p.id === 'medbot')!, ...projects.filter(p => p.id !== 'medbot')];
const filters = ['All projects', 'Web & apps', 'AI & ML', 'Robotics'];
const stories = [
  { id: 'nexamart', label: 'FULL-STACK E-COMMERCE', title: 'A high-speed MERN engine.\nBuilt for enterprise scale.', copy: 'NexaMart combines MongoDB Atlas, Express REST APIs, React 19, and Node.js microservices with Redis sub-50ms caching and Stripe Elements payment gateway.', points: ['MERN Stack architecture (MongoDB, Express, React, Node)', 'Redis caching & Stripe 256-bit SSL gateway', 'Redux Toolkit state engine & admin telemetry'] },
  { id: 'asaan-mazdoor', label: 'CONNECTED EXPERIENCES', title: 'A marketplace with two sides.\nOne connected journey.', copy: 'Asaan Mazdoor brings customers and professionals into a shared service marketplace. Role-based mobile screens connect discovery, jobs, profiles, orders, and communication.', points: ['Customer and professional experiences', 'Service discovery and order management', 'React Native with an Express backend'] },
  { id: 'medbot', label: 'INTELLIGENCE IN MOTION', title: 'From a sentence\nto a robot mission.', copy: 'MedBot connects natural language with purposeful movement. Instructions pass through intent recognition, clarification, and plan validation before a robot navigates the simulated hospital.', points: ['Language understanding and task planning', 'Validated plans and A* navigation', 'Recorded Webots mission demonstrations'] },
  { id: 'api-test-lab', label: 'TOOLS FOR BUILDERS', title: 'Turn an API contract\ninto a clearer test workflow.', copy: 'API Test Evidence Lab brings specification import, AI-assisted test generation, request validation, and execution evidence into a focused developer workspace.', points: ['OpenAPI and Swagger import', 'Structured generation and validation', 'Reviewable execution reports'] },
];

const skillGroups = [
  { label: 'Frontend', color: '#c8f479', items: ['React 19', 'Redux Toolkit', 'TypeScript', 'Next.js', 'React Native', 'Tailwind CSS', 'Vite'] },
  { label: 'Backend & Cloud', color: '#79d4f4', items: ['Node.js', 'Express.js', 'FastAPI', 'Python', 'REST APIs', 'Socket.IO', 'Docker'] },
  { label: 'Databases & Cache', color: '#f479c8', items: ['MongoDB Atlas', 'Redis Cache', 'PostgreSQL', 'Prisma'] },
  { label: 'Payment & APIs', color: '#79f4c8', items: ['Stripe API', 'JWT Auth', 'Claude API', 'OpenAPI / Swagger'] },
  { label: 'AI & ML', color: '#f4c879', items: ['PyTorch', 'Transformers', 'YOLOv8', 'OpenCV', 'scikit-learn', 'FinBERT'] },
  { label: 'Robotics', color: '#c879f4', items: ['Webots', 'ROS', 'A* Navigation', 'MediaPipe', 'Vosk', 'Whisper'] },
];

const timeline = [
  { year: '2026', type: 'edu', icon: GraduationCap, title: 'Bachelor of Computer Science', place: 'Islamabad, Pakistan', detail: 'Graduated with focus on Software Engineering, Artificial Intelligence, and Robotics.' },
  { year: '2025', type: 'work', icon: Briefcase, title: 'Freelance Developer & AI Builder', place: 'Remote', detail: 'Built apps, AI systems, and robotics projects: from mobile marketplaces to autonomous robots in simulation.' },
  { year: '2024', type: 'work', icon: Star, title: 'Final Year Projects', place: 'University & Client Work', detail: 'Delivered MedBot (AI+Robotics), API Test Evidence Lab, and multiple full-stack projects.' },
  { year: '2023', type: 'edu', icon: Code2, title: 'Deep Dive into AI & ML', place: 'Self-directed learning', detail: 'Studied deep learning, computer vision with YOLO, NLP with Transformers, and model evaluation.' },
];

export default function Home() {
  const [selected, setSelected] = useState<Project | null>(null);
  const [filter, setFilter] = useState('All projects');
  const visibleProjects = projects.filter(p => filter === 'All projects' || (filter === 'Web & apps' && /Web|Mobile/.test(p.category)) || (filter === 'AI & ML' && /AI|vision/.test(p.category)) || (filter === 'Robotics' && /Robotics/.test(p.category)));
  return <>
    <a className="skip-link" href="#work">Skip to projects</a>
    <div className="hero-shell">
      <div className="hero-orbs" aria-hidden="true"><span className="orb orb-1" /><span className="orb orb-2" /><span className="orb orb-3" /></div>
      <header className="site-header wrap"><a className="brand" href="#"><span className="monogram">tt.</span><span>Tayyab Tufail<span className="brand-sub">DEVELOPER & AI BUILDER</span></span></a><nav aria-label="Main navigation"><a href="#work">My work</a><a href="#skills">Skills</a><a href="#expertise">Expertise</a><a href="#about">About</a></nav><div className="header-right"><a className="social-icon" href="https://github.com/Tayyab-Tufail" target="_blank" rel="noreferrer" aria-label="GitHub"><GithubIcon size={20} /></a><a className="social-icon" href="https://linkedin.com/in/tayyab-tufail" target="_blank" rel="noreferrer" aria-label="LinkedIn"><LinkedinIcon size={20} /></a><a className="header-contact" href="#contact">Let's talk <ArrowUpRight size={17} /></a></div></header>
      <section className="hero wrap" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> SOFTWARE DEVELOPMENT & INTELLIGENT SYSTEMS</p><h1 id="hero-title">Ideas into<br />working<br /><span>technology.</span></h1><p className="hero-description">I'm Tayyab Tufail. I build apps, websites, AI models, and robotics systems: connecting thoughtful software with practical problem-solving.</p><div className="hero-actions"><a href="#work" className="button button-lime">Explore my work <ArrowDown size={18} /></a><a className="text-link" href="mailto:tayyabmalik1655@gmail.com">Get in touch <ArrowUpRight size={17} /></a></div><div className="hero-badges"><span className="hero-badge"><span className="badge-dot" style={{background:'#c8f479'}} />React Native</span><span className="hero-badge"><span className="badge-dot" style={{background:'#79d4f4'}} />Python</span><span className="hero-badge"><span className="badge-dot" style={{background:'#f4c879'}} />YOLOv8</span><span className="hero-badge"><span className="badge-dot" style={{background:'#f479c8'}} />Webots</span></div><div className="hero-note"><MoveHorizontal size={16} /><span>Explore the spotlight. Every project has a story.</span></div></div><ProjectSpotlight projects={spotlightProjects} onOpen={setSelected} /></section>
      <div className="discipline-strip"><div className="wrap"><span>Web development</span><i>✳</i><span>Mobile apps</span><i>✳</i><span>AI & machine learning</span><i>✳</i><span>Robotics</span><i>✳</i><span>IT solutions</span></div></div>
    </div>
    <main>
      <section id="skills" className="skills-section"><div className="wrap"><Reveal><div className="section-heading"><div><p className="eyebrow">02 / SKILLS & TECHNOLOGY</p><h2>Tools I work with.<br /><span>Across the full stack.</span></h2></div><p>A range of technologies across interfaces, AI pipelines, and backend systems.</p></div></Reveal><div className="skill-groups">{skillGroups.map(group => <Reveal key={group.label}><div className="skill-group"><p className="skill-group-label" style={{color: group.color}}>{group.label}</p><div className="skill-tags">{group.items.map(item => <span key={item} className="skill-tag">{item}</span>)}</div></div></Reveal>)}</div></div></section>
      <section className="work-section wrap"><Reveal><div className="section-heading"><div><p className="eyebrow">03 / THE PORTFOLIO</p><h2>Built to solve.<br /><span>Made to work.</span></h2></div><p>Applications, experiments, and intelligent systems. Open a project to explore its purpose, technical approach, images, and results.</p></div></Reveal><div id="work" className="collection-label"><span>PROJECT COLLECTION</span><span aria-live="polite">{visibleProjects.length} projects · Explore every detail</span></div><div className="project-filters" aria-label="Filter projects">{filters.map(item => <button key={item} aria-pressed={filter === item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="project-grid">{visibleProjects.map(p => <Reveal key={p.id}><ProjectCard project={p} index={projects.indexOf(p)} onOpen={setSelected} /></Reveal>)}</div></section>
      <section className="stories-section"><div className="wrap"><Reveal><div className="section-heading"><div><p className="eyebrow">04 / A CLOSER LOOK</p><h2>Different challenges.<br /><span>The same attention to detail.</span></h2></div><p>A few projects that bring interfaces, systems, and intelligent behavior together.</p></div></Reveal><div className="feature-stories">{stories.map((story, i) => { const p = projects.find(item => item.id === story.id)!; return <Reveal key={p.id}><article className={'feature-story ' + (i % 2 ? 'story-reverse' : '')}><button className={'story-image story-image-' + p.id} onClick={() => setSelected(p)} aria-label={'Open ' + p.title}><img src={'/images/' + p.images[0].file} alt={p.images[0].caption} loading="lazy" /><span className="story-image-label">{p.title}<ArrowUpRight size={20} /></span></button><div className="story-copy"><p className="eyebrow">{story.label}</p><h3>{story.title}</h3><p>{story.copy}</p><ul>{story.points.map(point => <li key={point}><Check size={17} />{point}</li>)}</ul><button className="text-link" onClick={() => setSelected(p)}>Inside {p.title} <ArrowUpRight size={18} /></button></div></article></Reveal>; })}</div></div></section>
      <section id="expertise" className="expertise-section"><div className="wrap"><Reveal><div className="section-heading"><div><p className="eyebrow">05 / WHAT I DO</p><h2>One builder.<br /><span>Multiple disciplines.</span></h2></div><p>From the interface people use to the intelligence behind it.</p></div></Reveal><div className="services">{[{ icon: Code2, title: 'Web development', text: 'Responsive websites, dashboards, APIs, and connected web applications.' }, { icon: Smartphone, title: 'Mobile applications', text: 'Cross-platform mobile experiences built with React Native and Expo.' }, { icon: Cpu, title: 'AI & machine learning', text: 'Computer vision, NLP, predictive models, and meaningful evaluation.' }, { icon: Bot, title: 'Robotics & automation', text: 'Perception, command understanding, navigation, and simulated autonomous systems.' }, { icon: Layers3, title: 'Data & IT solutions', text: 'Data pipelines, API testing, analytics, and tools that make workflows easier.' }].map(s => <article key={s.title}><s.icon size={27} strokeWidth={1.5} /><h3>{s.title}</h3><p>{s.text}</p></article>)}</div><div className="toolkit"><p className="eyebrow">TOOLS ACROSS THE WORK</p>{['React', 'TypeScript', 'React Native', 'Expo', 'Python', 'FastAPI', 'Node.js', 'MongoDB', 'PyTorch', 'Transformers', 'YOLO', 'OpenCV', 'scikit-learn', 'Webots'].map(tool => <span key={tool}>{tool}</span>)}</div></div></section>
      <section className="process-section wrap"><Reveal><div className="section-heading"><div><p className="eyebrow">06 / THE DEVELOPMENT PROCESS</p><h2>Good work starts<br /><span>with a clear question.</span></h2></div><p>A practical path from understanding a problem to making the result easy to explore.</p></div></Reveal><div className="process-grid">{[{ title: 'Understand', text: 'Define the user, the problem, and the outcome. Identify the data, constraints, and essential workflows.' }, { title: 'Design', text: 'Shape the screens and system structure. Choose the tools that fit the job and connect the important pieces.' }, { title: 'Build & evaluate', text: 'Implement the experience, test the workflow, and inspect model results with clear evaluation criteria.' }, { title: 'Explain & deliver', text: 'Document the approach and its limits. Share the interface, outputs, and evidence so the work can be understood.' }].map((step, i) => <Reveal key={step.title}><article><span className="process-number">0{i + 1}</span><h3>{step.title}</h3><p>{step.text}</p></article></Reveal>)}</div></section>
      <section id="about" className="about-section wrap"><p className="eyebrow">07 / A LITTLE ABOUT ME</p><Reveal><h2>Curiosity across disciplines.<br /><span>Care in the details.</span></h2><p>I’m Tayyab Tufail, a developer working across apps, websites, artificial intelligence, machine learning, and robotics. I enjoy turning complex ideas into software people can understand and use.</p><p>My projects bring together interface development, data preparation, model evaluation, and system integration. Some begin with a mobile experience; others start with a dataset, a language model, or a robot in simulation.</p><p>Across that variety, I care about the same things: a clear purpose, thoughtful implementation, and results that can be inspected. This portfolio brings those projects and their original outputs together in one place.</p><div className="about-signature"><span className="monogram">tt.</span><div>Tayyab Tufail<small>Software · Intelligence · Automation</small></div></div></Reveal></section>
      <section className="timeline-section wrap"><Reveal><div className="section-heading"><div><p className="eyebrow">08 / EXPERIENCE & BACKGROUND</p><h2>My journey so far.<br /><span>Education & milestones.</span></h2></div><p>Key steps along the way in software development, AI research, and independent building.</p></div></Reveal><div className="timeline-grid">{timeline.map((item, i) => <Reveal key={item.title}><article className="timeline-item"><div className="timeline-marker"><item.icon size={20} /><span>{item.year}</span></div><div className="timeline-content"><h3>{item.title}</h3><p className="timeline-place">{item.place}</p><p>{item.detail}</p></div></article></Reveal>)}</div></section>
      <section id="contact" className="contact-section"><div className="wrap"><Reveal><p className="eyebrow">09 / LET'S BUILD SOMETHING</p><h2>Have an idea?<br /><span>Let's make it work.</span></h2><p className="contact-intro">A website, an app, an AI experiment, or an automation challenge: tell me what you have in mind.</p></Reveal><div className="contact-links"><a href="mailto:tayyabmalik1655@gmail.com"><Mail size={22} /><span><small>EMAIL ME</small>tayyabmalik1655@gmail.com</span><ArrowUpRight /></a><a href="https://wa.me/923455788896" target="_blank" rel="noreferrer"><MessageCircle size={22} /><span><small>CHAT ON WHATSAPP</small>+92 345 5788896</span><ArrowUpRight /></a><a href="https://github.com/Tayyab-Tufail" target="_blank" rel="noreferrer"><GithubIcon size={22} /><span><small>GITHUB</small>github.com/tayyabtufail</span><ArrowUpRight /></a><a href="https://linkedin.com/in/tayyab-tufail" target="_blank" rel="noreferrer"><LinkedinIcon size={22} /><span><small>LINKEDIN</small>linkedin.com/in/tayyab-tufail</span><ArrowUpRight /></a></div><footer><a className="brand" href="#"><span className="monogram">tt.</span>Tayyab Tufail</a><span>Apps. Web. AI. Robotics.</span><div className="footer-social"><a href="https://github.com/Tayyab-Tufail" target="_blank" rel="noreferrer" aria-label="GitHub"><GithubIcon size={18} /></a><a href="https://linkedin.com/in/tayyab-tufail" target="_blank" rel="noreferrer" aria-label="LinkedIn"><LinkedinIcon size={18} /></a></div><a href="#">Back to top ↑</a></footer></div></section>
    </main>
    <ProjectDialog project={selected} onClose={() => setSelected(null)} />
  </>;
}
